name: Docs

on:
  workflow_dispatch:
  release:
    types:
      - created
  push:
    tags: *

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-devel-latest

      - name: Setup Nim Enviroment
      - uses: actions/checkout@master@v2
      - uses: iffy/install-nim@v3

      - name: Generate Documentation
        run: |
          nimble update
          nimble genDoc

      - name: deploy docs
        uses: appleboy/gh-pages-action@master
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          target_branch: master
          target_directory: docs
          remote_url: https://github.com/ire4ever1190/mike.git