
name: Tests

on: [push, pull_request]
  

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: ['1.4.0', 'stable', 'devel' ]
      fail-fast: false
      max-parallel: 3

    name: Nim ${{ matrix.nim }}
    steps:
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ matrix.nim }}-${{ hashFiles('taskman.nimble') }}
        
    - name: Setup Nim Enviroment
      uses: actions/checkout@master
    - uses: jiro4989/setup-nim-action@v1
      with:
          nim-version: ${{ matrix.nim }}
    - name: Update nimble
      run: nimble update

    - name: Run Tests
      run: nimble test
