
name: Tests

on:
  push:
    branches:
      - master
  pull_request:
  

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: ['1.6.0', 'stable', 'devel']
      fail-fast: false
      max-parallel: 3

    name: Nim ${{ matrix.nim }}
    steps:
    - name: Setup Nim Enviroment
      uses: actions/checkout@master

    - uses: jiro4989/setup-nim-action@v1
      with:
          nim-version: ${{ matrix.nim }}

    - name: Update nimble
      run: nimble update

    - name: Run tests
      run: nimble test

    - name: Test doc examples
      run: nimble doc src/taskman.nim

  deploy:
    needs: test
    permissions:
      pages: write # To deploy to Pages
      id-token: write # Verify deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: "Setup nim"
        uses: jiro4989/setup-nim-action@v1

      - name: "Build documentation"
        uses: ire4ever1190/nim-docs-action@v1
        with:
          main-file: "src/taskman.nim"
          deploy: "pages"
